### ISSUE TITLE
activeOnlyInside  does not work right

### ISSUE THREAD

**Issue by danyj** [hellsan631/LogosDistort#10]
I think this option should distort only when I position mouse inside the container
but even if I scroll down the page the animation continues. 

Just found out that the option was not used in plugin at all.

**Comment by hellsan631** [comment]
Ah, good feature. I will work to add this, or someone can post a PR :)

**Comment by danyj** [comment]
here is where the condition should go

https://github.com/hellsan631/LogosDistort/blob/master/src/jquery.logosDistort.js#L59

```
this.element
```

instead document , but since you said you are redoing the whole thing I rather wait than mess around.

**Comment by hellsan631** [comment]
solved by PR #12

By default, the effect is active when the mouse is inside of the container. I added a couple of different options for this. [See the new demo5](http://hellsan631.github.io/LogosDistort/demo5.html) or options for more details
