### ISSUE TITLE
Demos not working on different browsers

### ISSUE THREAD

**Issue by arkdy** [hellsan631/LogosDistort#20]
Hi,
First of all, thanks for the great plugin.
It seems like current version is not working properly in recent browsers (except Chrome).
But some of previous versions works fine (http://www.jqueryscript.net/demo/jQuery-Plugin-For-3D-Perspective-Transforms-On-Mousemove-LogosDistort/demo2.html)
Thanks!

**Comment by hellsan631** [comment]
I re-wrote the plugin to be native javascript, but this is important to me as well. I will make sure to check this in the next few days, but for now, everything should be the same between versions. For now though, you should use v0.2, https://github.com/hellsan631/LogosDistort/tree/v0.2.0

**Comment by hellsan631** [comment]
Just put out a small patch, very easy issue to fix. Chrome and FF have different returns for their events, so I just quickly patched what the event looks like for FF to make it compatible.

**Comment by arkdy** [comment]
Hey, it is awesome!
Thank you very much for quick fix and response. Keep up! :)
