### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by romain-lgr** [hellsan631/LogosDistort#21]
Hey,
It does not work on Safari. I am trying to find a fix for this, not very successful so far... If anyone has a hint / fix, please let me know.
Thank you :)

**Comment by romain-lgr** [comment]
Actually it was just a CSS issue, I fixed it by changing this:
-webkit-transform-style:flat;
to
-webkit-transform-style:preserve-3d;

Cheers,

**Comment by hellsan631** [comment]
ah good catch. sorry, i dont have a mac so not able to debug. im going to keep this open until i fix this issue though
