### ISSUE TITLE
How can I use <p> tag instead of creating image for my text?

### ISSUE THREAD

**Issue by kashcode** [hellsan631/LogosDistort#22]
If there any option for that?

**Comment by hellsan631** [comment]
You can use what ever tags you want for you text. Whats important is that its wrapped by a div, which will become the 3d target.

```
<div id="demo1">
  <img alt="background" src="assets/images/background.png" />
  <div id="text-here" >
    <p>You can write some text here</p>
  </div>
  <img alt="logo" src="assets/images/logo.png" />
</div>
```

``` js
$("#demo1").logosDistort();
```

**Comment by kashcode** [comment]
Hmm., I try it in Chrome and FF my custom text is positioned outside of screen, and it seems that for div tags css attributes width and height need replace with top and left.

**Comment by hellsan631** [comment]
you would need to absolutely position your text in the center of the container
