### ISSUE TITLE
Question about the UI

### ISSUE THREAD

**Issue by moon-mu** [hellsan631/LogosDistort#26]
Hi, 

Great plugin thank you! I am going to use it for my uni project.

However, I am really stuck and looking for help.

If we take for example the Demo3: http://hellsan631.github.io/LogosDistort/demo3.html

How do I put UI like links and buttons (or html image map) on top of the scene? I mean they to move with the rest while still remain clickable. 

What i have so far is the content is showing and moving but no clicks allowed.

In general clicking on elements during CSS transform is possible: http://jsfiddle.net/Zeaklous/x66yn/13/

Any help and directions will be highly appreciated.

Thank you for your time,

**Comment by hellsan631** [comment]
you need to be looking at the z-index of your elements to layer them correctly

**Comment by moon-mu** [comment]
pointer-events: auto was the key
