### ISSUE TITLE
Non Full screen version

### ISSUE THREAD

**Issue by REPTILEHAUS** [hellsan631/LogosDistort#9]
Is it possible to create this for a number of smaller divs rather than one full screen.. hellomondays project page for example ?

**Comment by hellsan631** [comment]
Yes, but I haven't tested it yet. That page effect though needs a different mouse tracker, and ill see to doing some dev work to create one.

**Comment by REPTILEHAUS** [comment]
I think I've managed to do it but all I did was change all the innerwidth
and inmerheights to just width height and I added two new parameters that I
can insert the width and height I need it to be.. Seems to work ok to me 😁

**Comment by hellsan631** [comment]
Do you think you could post an example? I was thinking of doing it a different way and creating some different mouse rules, to try and emulate that page better.

**Comment by REPTILEHAUS** [comment]
Yeah sure, where do I post it? I'm terrible at JavaScript so my version is
pretty hacky but it seems to work.

**Comment by hellsan631** [comment]
A [jsfiddle](https://jsfiddle.net/) would work great. let me know if you need any help with implementation with it.

**Comment by danyj** [comment]
+1 
I need to use this inside sections rather than full screen , 

like 

```
<section>

  <div id="demo">img.....</div>
</section>
```

so it would be great if we can get param for container and you than switch to take width and height from the container element instead from the screen

**Comment by danyj** [comment]
Example , 

in this demo 
https://jsfiddle.net/jqj1w1km/

 I have section set to 800x500  and I am on 27" monitor so I get this 

http://prntscr.com/8gjq5h

but perfect use case would be demo2 , scroll down on thjat fiddle 
where we get to distort the container instead of adding img inside the containers

**Comment by hellsan631** [comment]
There is a param for container. although its untested, feel free to see if it works!.

https://github.com/hellsan631/LogosDistort#options

Option 9

_edit_ ah, you found it.

I'm going to redo the entire plugin using javascript only, (it will work with jquery as well, the docs shouldn't change at all). This way I should have more options for performance optimizations. After doing this (i should be done soon), I will work on getting this feature implemented and officially supported.

**Comment by hellsan631** [comment]
solved by PR #12
